
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-extension-ethantang-top-ethantang-top-v1-service
  failurePolicy: Fail
  name: mservice.kb.io
  rules:
  - apiGroups:
    - extension.ethantang.top
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-extension-ethantang-top-ethantang-top-v1-service
  failurePolicy: Fail
  name: vservice.kb.io
  rules:
  - apiGroups:
    - extension.ethantang.top
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: None
