apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plain: proxy-daemon
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxy-daemon
  namespace: system
  labels:
    control-plain: proxy-daemon
spec:
  selector:
    matchLabels:
      control-plain: proxy-daemon
  template:
    metadata:
      labels:
        control-plain: proxy-daemon
    spec:
      hostNetwork: true
      containers:
      - command:
        - /proxy-daemon
        image: "proxy-daemon:latest"
        imagePullPolicy: Always
        name: proxy-daemon
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
